# -*- coding: utf-8 -*-
"""More Seaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13E7RVt40K8QCFCGYlH9lrLgvrraud32V
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

#barplot
df=sns.load_dataset('titanic')
df.head()

sns.barplot(x='class',y='fare',data=df)

sns.barplot(x='class',y='fare',data=df,hue='sex')

sns.barplot(x='class',y='fare',data=df,hue='sex',palette='inferno')

sns.barplot(x='class',y='fare',data=df,hue='sex',palette='inferno',orient='h')
#give error as y need to be a numeric in horizontal

sns.barplot(y='class',x='fare',data=df,hue='sex',palette='inferno',orient='h')

#estimator
sns.barplot(x='class',y='fare',data=df,hue='sex',palette='inferno',orient='v',estimator=np.sum)

#confidence interval

sns.barplot(x='class',y='fare',data=df,hue='sex'
            ,palette='inferno',orient='v',estimator=np.sum,ci=100,
            errcolor='red',errwidth=10)
#err is the black line in middle

#saturation
sns.barplot(x='class',y='fare',data=df,hue='sex'
            ,palette='inferno',orient='v',estimator=np.sum,ci=100,
            errcolor='red',errwidth=10,saturation=0.1)

#heatmaps
flight_df=sns.load_dataset('flights')
# flight_df=flight_df.pivot("month","years","passengers")
# flight_df
flight_df.head()

flight_df = sns.load_dataset('flights')
flight_df = flight_df.pivot(index="month", columns="year", values="passengers")
flight_df.head()

plt.figure(figsize=(12,6))
sns.heatmap(flight_df)

plt.figure(figsize=(12,6))
ax=sns.heatmap(flight_df,annot=True)
ax
#add values

plt.figure(figsize=(12,6))
ax=sns.heatmap(flight_df,annot=True,fmt='d')
ax

plt.figure(figsize=(12,6))
ax=sns.heatmap(flight_df,annot=True,fmt='d',linecolor='k',linewidth='5')
ax
#line color k represent black color
#line width space between blocks

plt.figure(figsize=(12,6))
ax=sns.heatmap(flight_df,annot=True,fmt='d',linecolor='k',linewidth='5',cmap='Blues')
ax
ax

plt.figure(figsize=(12,6))
ax=sns.heatmap(flight_df,annot=True,fmt='d',linecolor='k',linewidth='5',cbar=False)
ax

grid__kws ={"height_ratios":(.4,.05),"hspace":.4}
f,(ax,cbar_ax)=plt.subplots(2,gridspec_kw=grid__kws,figsize=(12,6))
ax=sns.heatmap(flight_df,cbar_kws={"orientation":"horizontal"},ax=ax,cbar_ax=cbar_ax)

titanic_df=sns.load_dataset('titanic')
titanic_df.head()

# Convert the 'sex' column to numerical values
titanic_df['sex'] = titanic_df['sex'].map({'male': 0, 'female': 1})

# Select only numerical columns for correlation calculation
numerical_titanic_df = titanic_df.select_dtypes(include=['number'])

# Now calculate the correlation matrix
numerical_titanic_df.corr()

plt.figure(figsize=(12,8))
sns.heatmap(numerical_titanic_df.corr())

#pair plot

penguins=sns.load_dataset('penguins')
penguins.head()

plt.figure(figsize=(12,6))
sns.pairplot(penguins)

sns.pairplot(penguins,hue='sex',palette='Reds')

sns.pairplot(penguins,hue='species',palette='Blues')

sns.pairplot(penguins,kind='kde',palette="Greens")

sns.pairplot(penguins,kind='hist',palette='Greens')

sns.pairplot(penguins,hue='species',diag_kind='hist',palette='rainbow')

sns.pairplot(penguins,corner=True)
#plot only lower part

sns.pairplot(penguins,hue="species",markers=["o","s","D"],palette='inferno')