# -*- coding: utf-8 -*-
"""ScatterAndBarGraph

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp4DKfLXI4dTVjwKkySefT27gFTbruTX
"""

#matplotlib
# used for data visualization
# used for data analysis
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.style.use('dark_background')

rollno=[1,2,3,4,5,6,7,8,9,10]
marks=[10,20,30,40,50,60,70,80,90,100]

plt.scatter(rollno,marks)
plt.show()

plt.scatter(rollno,marks,color='green')
plt.show()
# change color of dots

plt.scatter(rollno,marks,color='green',marker='*')
plt.show()
# change dat with given marker

plt.figure(figsize=(12,8))
plt.scatter(rollno,marks,color='green')
plt.show()
# change size of figure

plt.figure(figsize=(8,8))
plt.scatter(rollno,marks,c='b',marker='o',s=20)
plt.show()
#bo-> blue with marker o
# s->marker size

#multiple plots on same graph
temp_pune=[25,34,21,45,28,6,43,18,7,2]
humidity_pune=[28,25,29,20,26,50,19,29,52,55]

temp_banglore=[34,35,36,37,28,27,26,25,31,20]
humidity_banglore=[40,38,36,35,42,44,41,40,34,45]

plt.figure(figsize=(8,8))
plt.plot(temp_pune,humidity_pune,c='r',marker='o',markersize=15)
plt.show()

plt.figure(figsize=(8,8))
plt.xticks(np.arange(0,60,5))
plt.yticks(np.arange(10,60,5))
plt.plot(temp_pune,humidity_pune,c='r',marker='o',markersize=15)
plt.xlabel('Temperature')
plt.ylabel('Humidity')

plt.show()
#

plt.figure(figsize=(8,8))
plt.xticks(np.arange(0,60,5))
plt.yticks(np.arange(10,60,5))
plt.plot(temp_pune,humidity_pune,c='r',marker='o',markersize=15)
plt.plot(temp_banglore,humidity_banglore,c='b',marker='o',markersize=15)
plt.xlabel('Temperature')
plt.ylabel('Humidity')

df=pd.read_csv('/content/IRIS.csv')
df.head()

plt.scatter(df['sepal_length'],df['sepal_width'])
plt.show()

plt.plot(df['sepal_length'],df['sepal_width'],'go')
plt.show()

plt.figure(figsize=(8,8))
plt.xticks(np.arange(1,10,0.5))
plt.yticks(np.arange(1,10,0.5))
plt.plot(df['sepal_length'],df['petal_length'],'go',alpha=0.5,markersize=8)
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.show()

rollno=[1,2,3,4,5,6,7,8,9,10]
marks=[10,20,30,40,50,60,70,80,90,100]

plt.plot(rollno,marks,'r-')
plt.show()

plt.plot(rollno,marks,linestyle='-')
plt.show()

plt.plot(rollno,marks,linestyle='--',color='#728569')
plt.show()

plt.plot(rollno,marks,linestyle=':',color='#728569')
plt.show()

# anotations
# solid ='-'
# dashed = '--'
# dotted = ':'
# dashdot ='-.'
# 'None'or''

plt.plot(rollno,marks,linestyle='-.',color='#eee')
plt.show()

plt.plot(rollno,marks,linestyle=':',color='#728569',linewidth=15)
plt.show()

study_hours=[2,3,4,4,5,6,7,7,8,9,9,10,11,11,12]
marks=[6,10,15,20,34,44,55,60,55,67,70,80,90,99,100]

plt.figure(figsize=(8,8))
plt.xticks(np.arange(0,15,1))
plt.yticks(np.arange(0,100,5))
plt.plot(study_hours,marks,linestyle='-',color='#eee',linewidth=4)
plt.xlabel('study_hours')
plt.ylabel('marks')
plt.show()

plt.figure(figsize=(8,8))
plt.xticks(np.arange(0,15,1))
plt.yticks(np.arange(0,100,5))
plt.plot(study_hours,marks,'r-')
plt.plot(study_hours,marks,'bo')
plt.xlabel('study_hours')
plt.ylabel('marks')
# plt.grid()
plt.show()