# -*- coding: utf-8 -*-
"""SomeBasicSeaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1efAo1E8c8kdFaX6s2uX65XxAJTjEk7
"""

#data visualization

import seaborn as sns

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#linear plots
roll_no=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
marks=[23,45,67,89,56,34,21,45,67,32,67,76,33,21,45]
sample_df=pd.DataFrame({'RollNo.':roll_no,'Marks':marks})
sample_df.head()

sns.lineplot(x='RollNo.',y='Marks',data= sample_df)
plt.title('Student Marks')

seaborn_df = sns.load_dataset('titanic')
seaborn_df.head()
#load from anywhere

dataset=pd.read_csv('/content/hr_data.csv')
dataset.head()

sns.lineplot(x='number_project',y='average_montly_hours',data=dataset)

sns.lineplot(x='promotion_last_5years',y='left',data=dataset)

plt.figure(figsize=(12,6))
sns.lineplot(x='department',y='left',data=dataset)

sns.lineplot(x='number_project',y='average_montly_hours',data=dataset,hue='left')

sns.lineplot(x='number_project',y='average_montly_hours',data=dataset,hue='department')

plt.figure(figsize=(12,6))
sns.lineplot(x='number_project',y='average_montly_hours',data=dataset,hue='left',style='department')

plt.figure(figsize=(12,6))
sns.lineplot(x='number_project',y='average_montly_hours',data=dataset,hue='left',style='department',legend=False)
#marking will be gone

plt.figure(figsize=(12,6))
sns.lineplot(x='number_project',y='average_montly_hours',data=dataset,hue='left',style='department',legend='full',palette='flare')

#dist plots

sns.distplot(dataset['time_spend_company'])

sns.distplot(dataset['left'])

sns.distplot(dataset['average_montly_hours'])

dataset.describe()

bins=[2,3,4,5,6,7,8,9,10]#bars
sns.distplot(dataset['time_spend_company'],bins= bins)
plt.xticks(bins)

bins=[2,3,4,5,6,7,8,9,10]#bars
sns.distplot(dataset['time_spend_company'],bins= bins,kde=False)#line will be gone
#sns.disp is allowed now

sns.distplot(dataset['time_spend_company'],bins= bins,hist=False)#bars disappear

sns.distplot(dataset['time_spend_company'],bins= bins,rug=True)#precisely marked data

sns.distplot(dataset['time_spend_company'],bins= bins,rug=True,hist_kws={'color':'red','edgecolor':'blue','linewidth':3,'alpha':0.5})#change properties of color and other

sns.distplot(dataset['time_spend_company'],bins= bins,rug=True,hist_kws={'color':'red','edgecolor':'blue','linewidth':3,'alpha':0.5},kde_kws={'color':'orange','linewidth':5})#change properties of color and other

sns.distplot(dataset['time_spend_company'],bins= bins,rug=True,color='blue',vertical=True)

#scatter plot
titanic_df=sns.load_dataset('titanic')
titanic_df.head()

sns.scatterplot(x='age',y='fare',data=titanic_df)

sns.scatterplot(x='age',y='fare',data=titanic_df,hue='alive')

plt.figure(figsize=(12,6))
sns.scatterplot(x='age',y='fare',data=titanic_df,hue='alive',style='class')
plt.title('Titanic Data Analysis')

plt.figure(figsize=(12,6))
sns.scatterplot(x='age',y='fare',data=titanic_df,hue='alive',style='class',palette='inferno')
plt.title('Titanic Data Analysis')

plt.figure(figsize=(12,6))
sns.scatterplot(x='age',y='fare',data=titanic_df,hue='alive',style='class',palette='gist_rainbow',alpha=0.5)
plt.title('Titanic Data Analysis')

plt.figure(figsize=(12,6))
sns.scatterplot(x='age',y='fare',data=titanic_df,hue='alive',style='class',palette='inferno')
plt.title('Titanic Data Analysis')
sns.lineplot(x='age',y='fare',data=titanic_df,color='green')

